### ISSUE TITLE
Filter by source and target branch

### ISSUE THREAD

**Issue by gdisanto** [jenkinsci/bitbucket-pullrequests-filter-plugin#1]
### What feature do you want to see added?

Filter a pull request by source and target branches. For example do not consider pull requests with source branch "develop".

I have no idea what is the easiest way this can be implemented but I had a look at the code and it looks like the BitbucketPullRequest (https://javadoc.jenkins.io/plugin/cloudbees-bitbucket-branch-source/com/cloudbees/jenkins/plugins/bitbucket/api/BitbucketPullRequest.html) class exposes a getId() method to retrieve the pr id.

The Id can be used to retrieve the "fromRef" and "toRef" details from the bitbucket api, for Bitbucket server "https://bitbucket-server.com/rest/api/1.0/projects/{project}/repos/{repo}/pull-requests/{id}".

**Comment by Nuh** [comment]
@gdisanto, thank you for a good idea!

Thanks to changes by @gab1one, this was implemented.
Thank you very much!

A new version has been released.
